var booksData = [
  {
    id: 0,
    title: "Atomic Habits",
    author: "James Clear",
    genre: "Self-Improvement",
    year: "2018",
    type: "hardcover",
    image: "picture/Atomic Habits.png",
    reserved: false,
    description:
      "A powerful book on building good habits and breaking bad ones.",
  },
  {
    id: 1,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    genre: "Fiction",
    year: "1960",
    type: "paperback",
    image: "picture/To Kill a Mockingbird.png",
    reserved: true,
    description:
      "A classic novel exploring themes of racial injustice and moral growth.",
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Dystopian",
    year: "1949",
    type: "ebook",
    image: "picture/1984.jpg",
    reserved: false,
    description:
      "A dystopian novel depicting a totalitarian society under constant surveillance.",
  },
  {
    id: 3,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    genre: "Classic",
    year: "1925",
    type: "hardcover",
    image: "picture/The Great Gatsby.jpg",
    reserved: false,
    description:
      "A classic novel that explores the decadence of the Jazz Age and the American Dream.",
  },
  {
    id: 4,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    genre: "Coming of Age",
    year: "1951",
    type: "paperback",
    image: "picture/The Catcher in the Rye.jpg",
    reserved: false,
    description:
      "A coming-of-age novel that follows the experiences of Holden Caulfield in New York City.",
  },
  {
    id: 5,
    title: "Harry Potter and the Sorcerer's Stone",
    author: "J.K. Rowling",
    genre: "Fantasy",
    year: "1997",
    type: "hardcover",
    image: "picture/Harry Potter and the Sorcerer's Stone.jpg",
    reserved: false,
    description:
      "The first book in the Harry Potter series, introducing readers to the magical world of Hogwarts.",
  },
  {
    id: 6,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    genre: "Fantasy",
    year: "1937",
    type: "ebook",
    image: "picture/The Hobbit.jpg",
    reserved: false,
    description:
      "A fantasy novel that follows the journey of Bilbo Baggins as he ventures to reclaim treasure guarded by a dragon.",
  },
  {
    id: 7,
    title: "The Hunger Games",
    author: "Suzanne Collins",
    genre: "Dystopian",
    year: "2008",
    type: "paperback",
    image: "picture/The Hunger Games.jpg",
    reserved: true,
    description:
      "The first book in the Hunger Games trilogy, set in a dystopian future where children fight to the death in televised events.",
  },
  {
    id: 8,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Classic",
    year: "1813",
    type: "hardcover",
    image: "picture/Pride and Prejudice.jpg",
    reserved: false,
    description:
      "A classic novel that explores themes of love, class, and societal expectations in early 19th-century England.",
  },
  {
    id: 9,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Philosophical",
    year: "1988",
    type: "ebook",
    image: "picture/The Alchemist.jpg",
    reserved: false,
    description:
      "A philosophical novel that follows the journey of Santiago, a young shepherd, in pursuit of his personal legend.",
  },
  {
    id: 10,
    title: "Lord of the Flies",
    author: "William Golding",
    genre: "Allegory",
    year: "1954",
    type: "paperback",
    image: "picture/Lord of the Flies.jpg",
    reserved: false,
    description:
      "An allegorical novel that explores the descent into savagery when a group of boys is stranded on a deserted island.",
  },
  {
    id: 11,
    title: "The Chronicles of Narnia",
    author: "C.S. Lewis",
    genre: "Fantasy",
    year: "1950",
    type: "hardcover",
    image: "picture/The Chronicles of Narnia.jpg",
    reserved: false,
    description:
      "A classic fantasy series that follows the adventures of children in the magical land of Narnia.",
  },
  {
    id: 12,
    title: "One Hundred Years of Solitude",
    author: "Gabriel Garcia Marquez",
    genre: "Magical Realism",
    year: "1967",
    type: "paperback",
    image: "picture/One Hundred Years of Solitude.jpg",
    reserved: false,
    description:
      "A landmark novel in the magical realism genre, exploring the Buendía family's history in the fictional town of Macondo.",
  },
  {
    id: 13,
    title: "Brave New World",
    author: "Aldous Huxley",
    genre: "Dystopian",
    year: "1932",
    type: "ebook",
    image: "picture/Brave New World.jpg",
    reserved: false,
    description:
      "A dystopian novel that explores a future society where technological advancements control every aspect of human life.",
  },
  {
    id: 14,
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    genre: "Non-Fiction",
    year: "2011",
    type: "hardcover",
    image: "picture/Sapiens.jpg",
    reserved: false,
    description:
      "A thought-provoking exploration of human history, from the emergence of Homo sapiens to the present day.",
  },
  {
    id: 15,
    title: "The Shining",
    author: "Stephen King",
    genre: "Horror",
    year: "1977",
    type: "paperback",
    image: "picture/The Shining.jpg",
    reserved: false,
    description:
      "A classic horror novel that tells the story of the Torrance family's winter stay at the haunted Overlook Hotel.",
  },
  {
    id: 16,
    title: "The Road",
    author: "Cormac McCarthy",
    genre: "Post-Apocalyptic",
    year: "2006",
    type: "ebook",
    image: "picture/The Road.jpg",
    reserved: false,
    description:
      "A post-apocalyptic novel following the journey of a father and son through a desolate and dangerous landscape.",
  },
  {
    id: 17,
    title: "The Girl on the Train",
    author: "Paula Hawkins",
    genre: "Thriller",
    year: "2015",
    type: "paperback",
    image: "picture/The Girl on the Train.jpg",
    reserved: false,
    description:
      "A psychological thriller centered around a woman who becomes entangled in a missing person's investigation.",
  },
  {
    id: 18,
    title: "Educated",
    author: "Tara Westover",
    genre: "Memoir",
    year: "2018",
    type: "hardcover",
    image: "picture/Educated.jpg",
    reserved: false,
    description:
      "A memoir recounting Tara Westover's journey from growing up in a strict and abusive household to earning a PhD from Cambridge University.",
  },
  {
    id: 19,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    genre: "Psychological Thriller",
    year: "2019",
    type: "ebook",
    image: "picture/The Silent Patient.jpg",
    reserved: false,
    description:
      "A psychological thriller revolving around a woman who shoots her husband and then stops speaking, leading to a gripping mystery.",
  },
  {
    id: 20,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    genre: "Mystery",
    year: "2018",
    type: "hardcover",
    image: "picture/Where the Crawdads Sing.jpg",
    reserved: false,
    description:
      "A mystery novel set in the marshes of North Carolina, exploring the life of Kya Clark, known as the 'Marsh Girl.'",
  },
];
